openapi: 3.0.1
info:
  title: fetchChessPlayers
  description: API Definition of fetchChessPlayers
  version: 1.0.0
servers:
- url: http://localhost:8290/api/v1/games
paths:
  /:
    get:
      responses:
        default:
          description: Default response
